version: "3.1"

services:
 app:
  image: lime:local
  hostname: limesapp
  container_name: limes_app
  ports:
    - 1337:1337
  expose:
    - 1337
  depends_on:
    - redis

 redis:
  image: redis:latest
  hostname: limesredis
  container_name: limes_redis
  