version: "3.1"

services:
 app:
  image: quay.io/mossnz/purplecon-limes:stage5
  hostname: limesapp
  container_name: limes_app
  ports:
    - 1337:1337
  expose:
    - 1337
  depends_on:
    - redis

 redis:
  image: quay.io/mossnz/purplecon-redis:stage5
  hostname: limesredis
  container_name: limes_redis
  