version: 2
jobs:
  checkout: 
    docker:
      - image: circleci/node:8.11-stretch
    working_directory: ~/checkout
    steps:
      - checkout
      - run:
          name: Generate Docker tag
          command: |
            FRIENDLY="`head -1 ~/checkout/app/FRIENDLY`"
            DOCKER_TAG="`date +%Y-%m-$FRIENDLY-$CIRCLE_BUILD_NUM`"
            echo $DOCKER_TAG > ~/checkout/tag
            echo $DOCKER_TAG
      - persist_to_workspace:
          root: ~/checkout
          paths: 
            - app/
            - docker-compose.yml
            - tag
 
  build-limes:
    docker:
      - image: circleci/node:8.11-stretch
    working_directory: ~/project
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Limes App
          command: |
            DOCKER_TAG="`head -1 tag`"
            docker build -t quay.io/mossnz/purplecon-limes:$DOCKER_TAG app/.
            docker save -o limes.tar quay.io/mossnz/purplecon-limes:$DOCKER_TAG
      - persist_to_workspace:
          root: ~/project
          paths:
            - limes.tar

  build-redis:
    docker: 
      - image: circleci/node:8.11-stretch
    working_directory: ~/project
    environment:
      REDIS_TAG: stage5
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Redis
          command: |
            docker build -t quay.io/mossnz/purplecon-redis:$REDIS_TAG app/services/redis/.
            docker save -o redis.tar quay.io/mossnz/purplecon-redis:$REDIS_TAG
      - persist_to_workspace:
          root: ~/project
          paths:
            - redis.tar

  check-redis:
    docker:
      - image: circleci/node:8.11-stretch
    environment:
      DIFF_VERSION: "v0.13.1"
    working_directory: /tmp/docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run: 
          name: Install container-diff
          command: |
            echo $DIFF_VERSION
            curl -LO https://storage.googleapis.com/container-diff/$DIFF_VERSION/container-diff-linux-amd64 
            chmod +x container-diff-linux-amd64 
            mkdir -p ~/bin 
            mv container-diff-linux-amd64 ~/bin/container-diff
      - run: 
          name: Container Diff
          command: |
            ~/bin/container-diff redis.tar remote://redis:latest

  push-limes:
    docker:
      - image: circleci/node:8.11-stretch
    working_directory: ~/project
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run: 
          name: Load Limes App
          command: |
            docker load -i limes.tar
      - run: 
          name: Push to Quay.io
          command: |
            DOCKER_TAG="`head -1 tag`"
            echo $QUAY_PWD | docker login -u="mossnz+circleci" --password-stdin quay.io
            docker push quay.io/mossnz/purplecon-limes:$DOCKER_TAG

workflows:
  version: 2

  ci_workflow:
    jobs:
      - checkout
      - build-limes:
          requires:
            - checkout
      - build-redis:
          requires:
            - checkout
      - check-redis:
          requires:
            - build-redis
      - approve-limes:
          type: approval
          requires:
            - build-limes
      - push-limes:
          requires:
            - approve-limes